// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if OPENGL
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#else
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;
float iTime;

float hash(float2 p)
{
    return frac((sin(dot(p, float2(269.5, 183.3))) * 43758.5453123));
}

float valueNoise(float2 p)
{
    float2 i = floor(p);
    float2 f = frac(p);
    float2 u = ((f * f) * (3.0 - (2.0 * f)));
    float a = hash((i + float2(0.0, 0.0)));
    float b = hash((i + float2(1.0, 0.0)));
    float c = hash((i + float2(0.0, 1.0)));
    float d = hash((i + float2(1.0, 1.0)));
    return lerp(lerp(a, b, u.x), lerp(c, d, u.x), u.y);
}

float fbm(float2 p)
{
    float sum = 0.0;
    float amp = 0.5;
    for (int i = 0; (i < 4); i++)
    {
        sum += (amp * valueNoise(p));
        p *= 2.0;
        amp *= 0.5;
    }
    return sum;
}

void mainImage(out float4 fragColor, float2 fragCoord)
{
    float2 uv = (fragCoord / iResolution.xy);
    float2 p = (uv * 4.0);
    float t = (iTime * 0.2);
    float2 q = float2(fbm((p + float2(0.0, 0.0))), fbm((p + float2(5.2, 1.3))));
    float2 r = float2(fbm(((p + (4.0 * q)) + float2((1.7 + t), 9.2))), fbm(((p + (4.0 * q)) + float2(8.3, (2.8 - t)))));
    float f = fbm((p + (4.0 * r)));
    float3 col = lerp(float3(0.10, 0.10, 0.35), float3(0.95, 0.55, 0.20), f);
    col = lerp(col, float3(0.20, 0.70, 0.50), clamp(length(q), 0.0, 1.0));
    col = lerp(col, float3(0.95, 0.95, 0.95), clamp((r.x * r.x), 0.0, 1.0));
    fragColor = float4(col, 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
