// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if OPENGL
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#else
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;

// GLSL mod(x,y) = x - y*floor(x/y) (sign follows y). HLSL fmod truncates toward
// zero, so for possibly-negative operands they differ. Use the GLSL-equivalent.
float  glsl_mod(float  x, float  y) { return x - y * floor(x / y); }
float2 glsl_mod(float2 x, float2 y) { return x - y * floor(x / y); }
float3 glsl_mod(float3 x, float3 y) { return x - y * floor(x / y); }
float4 glsl_mod(float4 x, float4 y) { return x - y * floor(x / y); }
float2 glsl_mod(float2 x, float  y) { return x - y * floor(x / y); }
float3 glsl_mod(float3 x, float  y) { return x - y * floor(x / y); }
float4 glsl_mod(float4 x, float  y) { return x - y * floor(x / y); }

void mainImage(out float4 fragColor, float2 fragCoord)
{
    float2 p = ((fragCoord - (0.5 * iResolution.xy)) / iResolution.y);
    float2 cell = glsl_mod((p * 8.0), 1.0);
    float checker = ((step(0.5, cell.x) == step(0.5, cell.y)) ? 1.0 : 0.0);
    fragColor = float4(checker, checker, checker, 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
