using System.Text;
using ShadowDusk.ShaderToy.Ast;

namespace ShadowDusk.ShaderToy;

/// <summary>
/// Wraps the translated GLSL body into a complete, self-contained legacy-FX9 <c>.fx</c>: the
/// referenced ShaderToy uniforms as HLSL globals, the <c>iChannelN</c> texture/sampler pairs, the
/// <c>glsl_mod</c> helper (when needed), a fullscreen-quad vertex shader, a pixel shader that
/// computes <c>fragCoord</c> (with the ShaderToy bottom-left Y origin) and calls <c>mainImage</c>,
/// and the <c>technique</c>/<c>pass</c> wrapper.
/// </summary>
internal sealed class HarnessGenerator
{
    private const string Tool = "ShadowDusk shadertoy2fx (Phase 46 experiment)";

    public string Generate(
        ConvertOptions options,
        IReadOnlyCollection<string> referencedUniforms,
        IReadOnlyList<CustomUniformDecl> customUniforms,
        IReadOnlyDictionary<string, string> customUniformDefaults,
        bool usedGlslMod,
        string translatedStructs,
        string translatedGlobals,
        string translatedFunctions)
    {
        var sb = new StringBuilder();

        // Header.
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// {options.EffectName} - generated by {Tool}");
        sb.AppendLine("// -----------------------------------------------------------------------------");
        sb.AppendLine("// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the");
        sb.AppendLine("// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and");
        sb.AppendLine("// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the");
        sb.AppendLine("// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();

        sb.AppendLine("#if OPENGL");
        sb.AppendLine("    #define VS_SHADERMODEL vs_3_0");
        sb.AppendLine("    #define PS_SHADERMODEL ps_3_0");
        sb.AppendLine("#else");
        sb.AppendLine("    #define VS_SHADERMODEL vs_3_0");
        sb.AppendLine("    #define PS_SHADERMODEL ps_3_0");
        sb.AppendLine("#endif");
        sb.AppendLine();

        EmitUniformGlobals(sb, referencedUniforms);
        EmitChannelSamplers(sb, referencedUniforms);
        EmitCustomUniforms(sb, customUniforms, customUniformDefaults);

        if (usedGlslMod)
        {
            sb.AppendLine("// GLSL mod(x,y) = x - y*floor(x/y) (sign follows y). HLSL fmod truncates toward");
            sb.AppendLine("// zero, so for possibly-negative operands they differ. Use the GLSL-equivalent.");
            sb.AppendLine("float  glsl_mod(float  x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine("float2 glsl_mod(float2 x, float2 y) { return x - y * floor(x / y); }");
            sb.AppendLine("float3 glsl_mod(float3 x, float3 y) { return x - y * floor(x / y); }");
            sb.AppendLine("float4 glsl_mod(float4 x, float4 y) { return x - y * floor(x / y); }");
            sb.AppendLine("float2 glsl_mod(float2 x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine("float3 glsl_mod(float3 x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine("float4 glsl_mod(float4 x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine();
        }

        // Translated user structs (+ their factory functions), then const globals, then functions.
        if (translatedStructs.Length > 0)
        {
            sb.Append(translatedStructs);
            sb.AppendLine();
        }

        if (translatedGlobals.Length > 0)
        {
            sb.Append(translatedGlobals);
            sb.AppendLine();
        }

        sb.Append(translatedFunctions);
        sb.AppendLine();

        EmitVertexShader(sb);
        EmitPixelShader(sb, referencedUniforms);
        EmitTechnique(sb, options.TechniqueName);

        return sb.ToString();
    }

    private static void EmitUniformGlobals(StringBuilder sb, IReadOnlyCollection<string> referenced)
    {
        bool any = false;
        foreach (string u in UniformInfo.ScalarUniforms)
        {
            if (referenced.Contains(u))
            {
                sb.AppendLine(UniformInfo.HlslDeclaration(u));
                any = true;
            }
        }

        // iResolution is needed by the harness PS to map uv -> fragCoord even if the body never
        // names it directly; ensure it is declared.
        if (!referenced.Contains("iResolution"))
        {
            sb.AppendLine("float3 iResolution;");
            any = true;
        }

        if (any)
        {
            sb.AppendLine();
        }
    }

    private static void EmitChannelSamplers(StringBuilder sb, IReadOnlyCollection<string> referenced)
    {
        bool any = false;
        foreach (string ch in UniformInfo.ChannelUniforms)
        {
            if (!referenced.Contains(ch))
            {
                continue;
            }

            sb.AppendLine($"texture {ch}Texture;");
            sb.AppendLine($"sampler2D {ch} = sampler_state");
            sb.AppendLine("{");
            sb.AppendLine($"    Texture = <{ch}Texture>;");
            sb.AppendLine("};");
            any = true;
        }

        if (any)
        {
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Emit each accepted custom <c>uniform</c> as a top-level HLSL global the consumer drives: a
    /// scalar/vector/matrix becomes a plain global (an effect parameter); a <c>sampler2D</c> becomes the
    /// same <c>texture &lt;name&gt;Texture; sampler2D &lt;name&gt; = sampler_state {...};</c> pair used for
    /// <c>iChannelN</c>, so <c>tex2D(&lt;name&gt;, uv)</c> works. All declared customs are emitted (the
    /// host drives them whether or not the body references them).
    /// </summary>
    private static void EmitCustomUniforms(
        StringBuilder sb,
        IReadOnlyList<CustomUniformDecl> customUniforms,
        IReadOnlyDictionary<string, string> customUniformDefaults)
    {
        if (customUniforms.Count == 0)
        {
            return;
        }

        sb.AppendLine("// Custom uniforms declared by the source shader. The host drives each as an");
        sb.AppendLine("// effect parameter (samplers via the matching <name>Texture).");
        bool any = false;
        foreach (CustomUniformDecl cu in customUniforms)
        {
            if (cu.IsSampler)
            {
                sb.AppendLine($"texture {cu.Name}Texture;");
                sb.AppendLine($"sampler2D {cu.Name} = sampler_state");
                sb.AppendLine("{");
                sb.AppendLine($"    Texture = <{cu.Name}Texture>;");
                sb.AppendLine("};");
            }
            else if (customUniformDefaults.TryGetValue(cu.Name, out string? def))
            {
                // G4: a uniform with a default value emits its default as the parameter's initializer.
                sb.AppendLine($"{TypeTable.ToHlsl(cu.TypeName)} {cu.Name} = {def};");
            }
            else
            {
                sb.AppendLine($"{TypeTable.ToHlsl(cu.TypeName)} {cu.Name};");
            }

            any = true;
        }

        if (any)
        {
            sb.AppendLine();
        }
    }

    private static void EmitVertexShader(StringBuilder sb)
    {
        sb.AppendLine("// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is");
        sb.AppendLine("// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.");
        sb.AppendLine("struct VSInput  { float4 Position : POSITION; };");
        sb.AppendLine("struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };");
        sb.AppendLine();
        sb.AppendLine("VSOutput VSMain(VSInput input)");
        sb.AppendLine("{");
        sb.AppendLine("    VSOutput output;");
        sb.AppendLine("    output.Position = input.Position;");
        sb.AppendLine("    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.");
        sb.AppendLine("    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);");
        sb.AppendLine("    return output;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitPixelShader(StringBuilder sb, IReadOnlyCollection<string> referenced)
    {
        sb.AppendLine("float4 PSMain(VSOutput input) : COLOR0");
        sb.AppendLine("{");
        sb.AppendLine("    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin");
        sb.AppendLine("    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the");
        sb.AppendLine("    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.");
        sb.AppendLine("    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;");
        sb.AppendLine("    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);");
        sb.AppendLine("    mainImage(fragColor, fragCoord);");
        sb.AppendLine("    return fragColor;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitTechnique(StringBuilder sb, string techniqueName)
    {
        sb.AppendLine($"technique {techniqueName}");
        sb.AppendLine("{");
        sb.AppendLine("    pass P0");
        sb.AppendLine("    {");
        sb.AppendLine("        VertexShader = compile VS_SHADERMODEL VSMain();");
        sb.AppendLine("        PixelShader  = compile PS_SHADERMODEL PSMain();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
