using System.Text;
using ShadowDusk.ShaderToy.Ast;

namespace ShadowDusk.ShaderToy;

/// <summary>
/// Wraps the translated GLSL body into a complete, self-contained legacy-FX9 <c>.fx</c>: the
/// referenced ShaderToy uniforms as HLSL globals, the <c>iChannelN</c> texture/sampler pairs, the
/// <c>glsl_mod</c> helper (when needed), a fullscreen-quad vertex shader, a pixel shader that
/// computes <c>fragCoord</c> (with the ShaderToy bottom-left Y origin) and calls <c>mainImage</c>,
/// and the <c>technique</c>/<c>pass</c> wrapper.
/// </summary>
internal sealed class HarnessGenerator
{
    private const string Tool = "ShadowDusk shadertoy2fx (Phase 46 experiment)";

    public string Generate(
        ConvertOptions options,
        IReadOnlyCollection<string> referencedUniforms,
        IReadOnlyList<CustomUniformDecl> customUniforms,
        IReadOnlyDictionary<string, string> customUniformDefaults,
        bool usedGlslMod,
        string translatedStructs,
        string translatedGlobals,
        string translatedFunctions,
        EntryMode entryMode = EntryMode.ShaderToy,
        string fragmentOutputName = "gl_FragColor",
        bool usedGlFragCoord = false,
        bool usedScreenUv = false,
        bool godotMode = false,
        string? returningReturnType = null)
    {
        var sb = new StringBuilder();

        // Header.
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// {options.EffectName} - generated by {Tool}");
        sb.AppendLine("// -----------------------------------------------------------------------------");
        if (entryMode == EntryMode.PlainGlsl)
        {
            sb.AppendLine("// This .fx wraps a single-pass plain-GLSL fragment shader ('void main()'). The host");
            sb.AppendLine("// MUST drive the resolution/time uniforms it references and draw a fullscreen quad in");
            sb.AppendLine("// NDC for anything to render. Legacy FX9 style so the existing ShadowDusk pipeline can");
            sb.AppendLine("// target OpenGL, DirectX, and FNA fx_2_0.");
        }
        else
        {
            sb.AppendLine("// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the");
            sb.AppendLine("// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and");
            sb.AppendLine("// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the");
            sb.AppendLine("// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.");
        }

        sb.AppendLine("// =============================================================================");
        sb.AppendLine();

        // The compile-target header is gated on SM4, which is exactly the macro MonoGame's
        // DirectX_11 shader profile defines (and OpenGL does not). It matters that the
        // DirectX arm asks for SM 4.0 level 9.1: mgfxc REJECTS anything lower for
        // /Profile:DirectX_11 ("Invalid profile 'vs_3_0'. Vertex shader 'VSMain' must be
        // SM 4.0 level 9.1 or higher!"), so a converted shader that asked for vs_3_0 there
        // was not compilable by the reference compiler at all. SM4 rather than the stock
        // '#if OPENGL ... #else' split because the #else arm also catches ShadowDusk's FNA
        // target, whose fx_2_0 output is capped at Shader Model 3 — gating on SM4 keeps
        // OpenGL AND FNA on the legacy profiles while giving DirectX the one it requires.
        sb.AppendLine("#if SM4");
        sb.AppendLine("    // DirectX (MonoGame's DirectX_11 profile defines SM4). mgfxc requires at least");
        sb.AppendLine("    // SM 4.0 level 9.1 here and rejects vs_3_0/ps_3_0 outright.");
        sb.AppendLine("    #define VS_SHADERMODEL vs_4_0_level_9_1");
        sb.AppendLine("    #define PS_SHADERMODEL ps_4_0_level_9_1");
        sb.AppendLine("#else");
        sb.AppendLine("    // OpenGL (mgfxc caps it at SM 3.0) and FNA fx_2_0 (MojoShader SM 2-3).");
        sb.AppendLine("    #define VS_SHADERMODEL vs_3_0");
        sb.AppendLine("    #define PS_SHADERMODEL ps_3_0");
        sb.AppendLine("#endif");
        sb.AppendLine();

        EmitUniformGlobals(sb, referencedUniforms);
        EmitChannelSamplers(sb, referencedUniforms);
        EmitCustomUniforms(sb, customUniforms, customUniformDefaults);

        if (usedGlslMod)
        {
            sb.AppendLine("// GLSL mod(x,y) = x - y*floor(x/y) (sign follows y). HLSL fmod truncates toward");
            sb.AppendLine("// zero, so for possibly-negative operands they differ. Use the GLSL-equivalent.");
            sb.AppendLine("float  glsl_mod(float  x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine("float2 glsl_mod(float2 x, float2 y) { return x - y * floor(x / y); }");
            sb.AppendLine("float3 glsl_mod(float3 x, float3 y) { return x - y * floor(x / y); }");
            sb.AppendLine("float4 glsl_mod(float4 x, float4 y) { return x - y * floor(x / y); }");
            sb.AppendLine("float2 glsl_mod(float2 x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine("float3 glsl_mod(float3 x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine("float4 glsl_mod(float4 x, float  y) { return x - y * floor(x / y); }");
            sb.AppendLine();
        }

        // G2: in plain-GLSL `main()` mode the fragment output and `gl_FragCoord` are file-scope
        // identifiers the body reads/writes. Emit each as a `static float4` global so the translated
        // `main()` (a regular HLSL function) can write the output and read gl_FragCoord, and the
        // synthesized PS bridges them (sets gl_FragCoord, calls main(), returns the output). A
        // user-declared `out vec4 <name>;` reuses the same mechanism under its own name; the legacy
        // `gl_FragColor` write target is just the default name.
        if (entryMode == EntryMode.PlainGlsl)
        {
            sb.AppendLine("// Plain-GLSL fragment I/O bridged as static globals (see PSMain below).");
            sb.AppendLine("static float4 gl_FragCoord;");
            sb.AppendLine($"static float4 {fragmentOutputName};");
            sb.AppendLine();
        }
        else if (usedGlFragCoord)
        {
            // G3c: a ShaderToy `mainImage` body that references gl_FragCoord directly. Publish it as a
            // static float4 the PS sets (from the same pixel coordinate it computes for fragCoord)
            // before calling mainImage, so the body's reads resolve.
            sb.AppendLine("// gl_FragCoord referenced by the body; bridged as a static global the PS sets.");
            sb.AppendLine("static float4 gl_FragCoord;");
            sb.AppendLine();
        }

        if (usedScreenUv)
        {
            // A screen-coordinate alias (ignored coordinate varying like vUv/texCoord/uv, or the OpenFL
            // openfl_TextureCoordv) was referenced. Publish the normalized screen UV as a static float2
            // the PS sets to fragCoord/iResolution.xy (ShaderToy bottom-left origin, [0,1]) before the
            // entry runs, so the body's reads resolve to the fullscreen UV.
            sb.AppendLine("// Screen-coordinate alias (ignored coordinate varying / openfl_TextureCoordv);");
            sb.AppendLine("// bridged as a static normalized screen UV the PS sets before the entry runs.");
            sb.AppendLine("static float2 sd_ScreenUV;");
            sb.AppendLine();
        }

        // Translated user structs (+ their factory functions), then const globals, then functions.
        if (translatedStructs.Length > 0)
        {
            sb.Append(translatedStructs);
            sb.AppendLine();
        }

        if (translatedGlobals.Length > 0)
        {
            sb.Append(translatedGlobals);
            sb.AppendLine();
        }

        sb.Append(translatedFunctions);
        sb.AppendLine();

        EmitVertexShader(sb);
        if (entryMode == EntryMode.PlainGlsl)
        {
            EmitPlainGlslPixelShader(sb, fragmentOutputName, usedScreenUv);
        }
        else if (godotMode)
        {
            EmitGodotPixelShader(sb, usedGlFragCoord, usedScreenUv);
        }
        else if (returningReturnType is not null)
        {
            EmitReturningPixelShader(sb, returningReturnType, usedGlFragCoord, usedScreenUv);
        }
        else
        {
            EmitPixelShader(sb, usedGlFragCoord, usedScreenUv);
        }

        EmitTechnique(sb, options.TechniqueName);

        return sb.ToString();
    }

    private static void EmitUniformGlobals(StringBuilder sb, IReadOnlyCollection<string> referenced)
    {
        bool any = false;
        foreach (string u in UniformInfo.ScalarUniforms)
        {
            if (referenced.Contains(u))
            {
                sb.AppendLine(UniformInfo.HlslDeclaration(u));
                any = true;
            }
        }

        // iResolution is needed by the harness PS to map uv -> fragCoord even if the body never
        // names it directly; ensure it is declared.
        if (!referenced.Contains("iResolution"))
        {
            sb.AppendLine("float3 iResolution;");
            any = true;
        }

        if (any)
        {
            sb.AppendLine();
        }
    }

    private static void EmitChannelSamplers(StringBuilder sb, IReadOnlyCollection<string> referenced)
    {
        bool any = false;
        foreach (string ch in UniformInfo.ChannelUniforms)
        {
            if (!referenced.Contains(ch))
            {
                continue;
            }

            sb.AppendLine($"texture {ch}Texture;");
            sb.AppendLine($"sampler2D {ch} = sampler_state");
            sb.AppendLine("{");
            sb.AppendLine($"    Texture = <{ch}Texture>;");
            sb.AppendLine("};");
            any = true;
        }

        if (any)
        {
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Emit each accepted custom <c>uniform</c> as a top-level HLSL global the consumer drives: a
    /// scalar/vector/matrix becomes a plain global (an effect parameter); a <c>sampler2D</c> becomes the
    /// same <c>texture &lt;name&gt;Texture; sampler2D &lt;name&gt; = sampler_state {...};</c> pair used for
    /// <c>iChannelN</c>, so <c>tex2D(&lt;name&gt;, uv)</c> works. All declared customs are emitted (the
    /// host drives them whether or not the body references them).
    /// </summary>
    private static void EmitCustomUniforms(
        StringBuilder sb,
        IReadOnlyList<CustomUniformDecl> customUniforms,
        IReadOnlyDictionary<string, string> customUniformDefaults)
    {
        if (customUniforms.Count == 0)
        {
            return;
        }

        sb.AppendLine("// Custom uniforms declared by the source shader. The host drives each as an");
        sb.AppendLine("// effect parameter (samplers via the matching <name>Texture).");
        bool any = false;
        foreach (CustomUniformDecl cu in customUniforms)
        {
            if (cu.IsSampler)
            {
                sb.AppendLine($"texture {cu.Name}Texture;");
                sb.AppendLine($"sampler2D {cu.Name} = sampler_state");
                sb.AppendLine("{");
                sb.AppendLine($"    Texture = <{cu.Name}Texture>;");
                sb.AppendLine("};");
            }
            else if (customUniformDefaults.TryGetValue(cu.Name, out string? def))
            {
                // G4: a uniform with a default value emits its default as the parameter's initializer.
                sb.AppendLine($"{TypeTable.ToHlsl(cu.TypeName)} {cu.Name} = {def};");
            }
            else
            {
                sb.AppendLine($"{TypeTable.ToHlsl(cu.TypeName)} {cu.Name};");
            }

            any = true;
        }

        if (any)
        {
            sb.AppendLine();
        }
    }

    private static void EmitVertexShader(StringBuilder sb)
    {
        sb.AppendLine("// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is");
        sb.AppendLine("// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.");
        sb.AppendLine("struct VSInput  { float4 Position : POSITION; };");
        sb.AppendLine("struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };");
        sb.AppendLine();
        sb.AppendLine("VSOutput VSMain(VSInput input)");
        sb.AppendLine("{");
        sb.AppendLine("    VSOutput output;");
        sb.AppendLine("    output.Position = input.Position;");
        sb.AppendLine("    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.");
        sb.AppendLine("    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);");
        sb.AppendLine("    return output;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitPixelShader(StringBuilder sb, bool usedGlFragCoord, bool usedScreenUv)
    {
        sb.AppendLine("float4 PSMain(VSOutput input) : COLOR0");
        sb.AppendLine("{");
        sb.AppendLine("    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin");
        sb.AppendLine("    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the");
        sb.AppendLine("    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.");
        sb.AppendLine("    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;");
        if (usedGlFragCoord)
        {
            // G3c: publish gl_FragCoord from the same pixel coordinate (.xy = fragCoord, .z = 0, .w = 1)
            // before calling mainImage, so a body that reads gl_FragCoord directly resolves.
            sb.AppendLine("    gl_FragCoord = float4(fragCoord, 0.0, 1.0);");
        }

        if (usedScreenUv)
        {
            // Publish the normalized screen UV ([0,1], same bottom-left origin as fragCoord) so a body
            // that reads a coordinate-varying / openfl_TextureCoordv alias resolves to the fullscreen UV.
            sb.AppendLine("    sd_ScreenUV = fragCoord / iResolution.xy;");
        }

        sb.AppendLine("    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);");
        sb.AppendLine("    mainImage(fragColor, fragCoord);");
        sb.AppendLine("    return fragColor;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Emit the pixel shader for the desktop-runner "returning" <c>mainImage</c> form
    /// (<c>vec3/vec4 mainImage(in vec2 fragCoord)</c>). It computes the same bottom-left-Y
    /// <c>fragCoord</c>, calls <c>mainImage(fragCoord)</c>, and returns the result as <c>COLOR0</c>. A
    /// <c>vec3</c> (float3) return is padded to <c>float4(rgb, 1.0)</c>; a <c>vec4</c> return is used as-is.
    /// </summary>
    private static void EmitReturningPixelShader(
        StringBuilder sb, string returningReturnType, bool usedGlFragCoord, bool usedScreenUv)
    {
        sb.AppendLine("float4 PSMain(VSOutput input) : COLOR0");
        sb.AppendLine("{");
        sb.AppendLine("    // 'returning' mainImage form: vec3/vec4 mainImage(in vec2 fragCoord) returns the");
        sb.AppendLine("    // color. Same bottom-left-Y fragCoord as the standard harness.");
        sb.AppendLine("    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;");
        if (usedGlFragCoord)
        {
            sb.AppendLine("    gl_FragCoord = float4(fragCoord, 0.0, 1.0);");
        }

        if (usedScreenUv)
        {
            sb.AppendLine("    sd_ScreenUV = fragCoord / iResolution.xy;");
        }

        if (returningReturnType == "vec3")
        {
            sb.AppendLine("    float3 rgb = mainImage(fragCoord);");
            sb.AppendLine("    return float4(rgb, 1.0);");
        }
        else
        {
            sb.AppendLine("    return mainImage(fragCoord);");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Emit the pixel shader for the Godot / GdShaders 3-parameter <c>mainImage</c> form
    /// (<c>in vec4 inputColor, in vec2 uv, out vec4 outputColor</c>). It computes the same bottom-left-Y
    /// <c>fragCoord</c>, derives Godot's normalized SCREEN_UV <c>uv = fragCoord / iResolution.xy</c>
    /// ([0,1]), samples <c>iChannel0</c> at <c>uv</c> as the screen-texture <c>inputColor</c>, calls
    /// <c>mainImage(inputColor, uv, outputColor)</c>, and returns <c>outputColor</c> as COLOR0.
    /// </summary>
    private static void EmitGodotPixelShader(StringBuilder sb, bool usedGlFragCoord, bool usedScreenUv)
    {
        sb.AppendLine("float4 PSMain(VSOutput input) : COLOR0");
        sb.AppendLine("{");
        sb.AppendLine("    // Godot/GdShaders mainImage: uv = SCREEN_UV ([0,1]); inputColor = the screen");
        sb.AppendLine("    // (iChannel0) sample at uv; outputColor = the returned color. Same bottom-left Y.");
        sb.AppendLine("    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;");
        sb.AppendLine("    float2 uv = fragCoord / iResolution.xy;");
        if (usedGlFragCoord)
        {
            sb.AppendLine("    gl_FragCoord = float4(fragCoord, 0.0, 1.0);");
        }

        if (usedScreenUv)
        {
            sb.AppendLine("    sd_ScreenUV = uv;");
        }

        sb.AppendLine("    float4 inputColor = tex2D(iChannel0, uv);");
        sb.AppendLine("    float4 outputColor = float4(0.0, 0.0, 0.0, 1.0);");
        sb.AppendLine("    mainImage(inputColor, uv, outputColor);");
        sb.AppendLine("    return outputColor;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Emit the pixel shader for plain-GLSL <c>void main()</c> mode (G2). It computes the SAME pixel
    /// coordinate the ShaderToy harness uses (bottom-left Y origin, so <c>gl_FragCoord.y</c> grows
    /// upward and renders in the reference orientation), publishes it as the <c>gl_FragCoord</c> static
    /// global (<c>.xy</c> = pixel coord, <c>.z</c> = 0, <c>.w</c> = 1), calls the translated
    /// <c>main()</c>, and returns the fragment-output static global as <c>COLOR0</c>.
    /// </summary>
    private static void EmitPlainGlslPixelShader(StringBuilder sb, string fragmentOutputName, bool usedScreenUv)
    {
        sb.AppendLine("float4 PSMain(VSOutput input) : COLOR0");
        sb.AppendLine("{");
        sb.AppendLine("    // Plain-GLSL gl_FragCoord has a BOTTOM-LEFT origin (y grows upward); our uv has a");
        sb.AppendLine("    // top-left origin (uv.y=0 at the top). Flip Y back so gl_FragCoord.y grows upward,");
        sb.AppendLine("    // matching the GLSL/ShaderToy reference orientation. .z=0, .w=1 like a real");
        sb.AppendLine("    // gl_FragCoord (depth/1-over-w are not meaningful for a fullscreen pass).");
        sb.AppendLine("    float2 pixel = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;");
        sb.AppendLine("    gl_FragCoord = float4(pixel, 0.0, 1.0);");
        if (usedScreenUv)
        {
            // Publish the normalized screen UV ([0,1]) for a coordinate-varying / openfl_TextureCoordv alias.
            sb.AppendLine("    sd_ScreenUV = pixel / iResolution.xy;");
        }

        sb.AppendLine($"    {fragmentOutputName} = float4(0.0, 0.0, 0.0, 1.0);");
        sb.AppendLine("    main();");
        sb.AppendLine($"    return {fragmentOutputName};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitTechnique(StringBuilder sb, string techniqueName)
    {
        sb.AppendLine($"technique {techniqueName}");
        sb.AppendLine("{");
        sb.AppendLine("    pass P0");
        sb.AppendLine("    {");
        sb.AppendLine("        VertexShader = compile VS_SHADERMODEL VSMain();");
        sb.AppendLine("        PixelShader  = compile PS_SHADERMODEL PSMain();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
