// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if OPENGL
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#else
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;
float iTime;

static const float PI = 3.141592654;
static const float TAU = (2. * PI);
static const float PI_2 = (.5 * PI);

float ray_issphere4(float3 ro, float3 rd, float ra)
{
    float r2 = (ra * ra);
    float3 d2 = (rd * rd);
    float3 d3 = (d2 * rd);
    float3 o2 = (ro * ro);
    float3 o3 = (o2 * ro);
    float ka = (1. / dot(d2, d2));
    float k3 = (ka * dot(ro, d3));
    float k2 = (ka * dot(o2, d2));
    float k1 = (ka * dot(o3, rd));
    float k0 = (ka * (dot(o2, o2) - (r2 * r2)));
    float c2 = (k2 - (k3 * k3));
    float c1 = ((k1 + (((2. * k3) * k3) * k3)) - ((3. * k3) * k2));
    float c0 = (((k0 - ((((3. * k3) * k3) * k3) * k3)) + (((6. * k3) * k3) * k2)) - ((4. * k3) * k1));
    float p = ((c2 * c2) + (c0 / 3.));
    float q = ((((c2 * c2) * c2) - (c2 * c0)) + (c1 * c1));
    float h = ((q * q) - ((p * p) * p));
    if (h < 0.)
    {
        return -1.;
    }
    float sh = sqrt(h);
    float s = (sign((q + sh)) * pow(abs((q + sh)), (1. / 3.)));
    float t = (sign((q - sh)) * pow(abs((q - sh)), (1. / 3.)));
    float2 w = float2((s + t), (s - t));
    float2 v = (float2((w.x + (c2 * 4.0)), (w.y * sqrt(3.0))) * 0.5);
    float r = length(v);
    return (((abs(v.y) / sqrt((r + v.x))) - (c1 / r)) - k3);
}

float hash(float2 co)
{
    return frac((sin(dot(co.xy, float2(12.9898, 58.233))) * 13758.5453));
}

float hash(float co)
{
    return frac((sin((co * 12.9898)) * 13758.5453));
}

float dot2(float2 p)
{
    return dot(p, p);
}

float3 lines(float3 F, float3 P, float A, float AA, float T)
{
    const float N = 4.;
    const float2 Z0 = float2(5e-3, (TAU / 6.));
    const float2 Z1 = (.2 * Z0);
    for (float j = 0.; j < N; ++j)
    {
        float3 p = P;
        float3 b;
        p.x += ((Z0.x * j) / N);
        float h0 = hash(float2(floor(((p.x / Z0.x) + .5)), j));
        float h1 = frac((8667.0 * h0));
        float a = (A - (T * (1. + h0)));
        float2 q = float2(p.x, a);
        float2 n = floor(((float2(p.x, a) / Z0) + .5));
        float2 q0;
        float2 q1;
        float2 d;
        q -= (n * Z0);
        q0 = (q - float2(0, Z1.y));
        q1 = q;
        q1.y = max((abs(q1.y) - Z1.y), 0.);
        d = (float2(length(q0), length(q1)) - Z1.x);
        float4 c = (.5 * (1. + sin((((.1 * T) + (TAU * h1)) + float4(0, 1, 8, 4)))));
        b = (c.xyz * c.w);
        F += ((exp((19. * (q.y - Z1.y))) * smoothstep(AA, -AA, d.y)) * b);
        F += (smoothstep(AA, -AA, (d.x - (.5 * Z1.x))) * sqrt((.5 * (b - min(0., (d.x - (.5 * Z1.x)))))));
    }
    return F;
}

float3 stars(float3 F, float3 P, float A, float AA, float T)
{
    const float2 Z0 = float2(.1, (TAU / 6.));
    float3 p = P;
    p.x += .123;
    float h0 = hash(float2(floor(((p.x / Z0.x) + .5)), 0));
    float h1 = frac((8667. * h0));
    float a = (A - (T * (1.5 + h0)));
    float2 q = float2(p.x, a);
    float2 n = floor(((float2(p.x, a) / Z0) + .5));
    float2 dq;
    q -= (n * Z0);
    dq = fwidth(q);
    float3 c = ((.5 * (1. + sin((((7. * T) + (TAU * h1)) + float3(2, 1, 0))))) * hash(((.123 * n.x) + floor((T * 121.)))));
    F += ((c.xyz * 7e-6) / max(dot2((float2((dq.y / dq.x), 1) * q)), 1e-6));
    return F;
}

void mainImage(out float4 O, float2 C)
{
    float2 R = iResolution.xy;
    float3 RO = float3(0., -1.9, -0);
    float3 RD = normalize(float3((C - (.5 * R)), (sqrt(2.) * R.y)));
    float3 F = ((3e-4 * float3(1, 4, 40)) / (dot2((float2(sqrt(.5), 1).yx * ((((C + C) - R) / R.x) - float2(0, (R.y / R.x))))) + 2e-3));
    float3 P;
    float Z = ray_issphere4(RO, RD, 2.);
    float A;
    float AA;
    float T = ((.07 * iTime) + 123.);
    P = ((Z * RD) + RO);
    A = atan2(P.z, P.y);
    AA = (sqrt(2.) * length(fwidth(float2(P.x, A))));
    F = lines(F, P, A, AA, T);
    F = stars(F, P, A, AA, T);
    F *= 4.;
    F -= (2e-2 * float3(2, 3, 1));
    F = tanh(F);
    F = max(F, 0.);
    F = (sqrt(F) - .05);
    O = float4(F, 1);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
