// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if SM4
    // DirectX (MonoGame's DirectX_11 profile defines SM4). mgfxc requires at least
    // SM 4.0 level 9.1 here and rejects vs_3_0/ps_3_0 outright.
    #define VS_SHADERMODEL vs_4_0_level_9_1
    #define PS_SHADERMODEL ps_4_0_level_9_1
#else
    // OpenGL (mgfxc caps it at SM 3.0) and FNA fx_2_0 (MojoShader SM 2-3).
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;
float iTime;

float hash(float2 p)
{
    return frac((sin(dot(p, float2(127.1, 311.7))) * 43758.5453123));
}

float valueNoise(float2 p)
{
    float2 i = floor(p);
    float2 f = frac(p);
    float2 u = ((f * f) * (3.0 - (2.0 * f)));
    float a = hash((i + float2(0.0, 0.0)));
    float b = hash((i + float2(1.0, 0.0)));
    float c = hash((i + float2(0.0, 1.0)));
    float d = hash((i + float2(1.0, 1.0)));
    return lerp(lerp(a, b, u.x), lerp(c, d, u.x), u.y);
}

float fbm(float2 p)
{
    float sum = 0.0;
    float amp = 0.5;
    float2x2 rot = float2x2(1.6, 1.2, -1.2, 1.6);
    for (int i = 0; i < 5; i++)
    {
        sum += (amp * valueNoise(p));
        p = mul(p, rot);
        amp *= 0.5;
    }
    return sum;
}

void mainImage(out float4 fragColor, float2 fragCoord)
{
    float2 uv = (fragCoord / iResolution.xy);
    float2 p = (uv * 3.0);
    p.x += (iTime * 0.1);
    float n = fbm(p);
    float clouds = smoothstep(0.35, 0.75, n);
    float3 sky = lerp(float3(0.30, 0.55, 0.85), float3(0.65, 0.80, 0.95), uv.y);
    float3 col = lerp(sky, ((float3)(1.0)), clouds);
    fragColor = float4(col, 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
