// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if SM4
    // DirectX (MonoGame's DirectX_11 profile defines SM4). mgfxc requires at least
    // SM 4.0 level 9.1 here and rejects vs_3_0/ps_3_0 outright.
    #define VS_SHADERMODEL vs_4_0_level_9_1
    #define PS_SHADERMODEL ps_4_0_level_9_1
#else
    // OpenGL (mgfxc caps it at SM 3.0) and FNA fx_2_0 (MojoShader SM 2-3).
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;
float iTime;
float4 iMouse;

float2x2 rot(float a)
{
    float c = cos(a);
    float s = sin(a);
    return float2x2(c, -s, s, c);
}

float2x2 Rot(float a)
{
    return rot(a);
}

float2 N(float angle)
{
    return float2(sin(angle), cos(angle));
}

float3 palette(float t)
{
    float3 a = float3(0.5, 0.5, 0.5);
    float3 b = float3(0.5, 0.5, 0.5);
    float3 c = float3(1.0, 1.0, 1.0);
    float3 d = float3(0.263, 0.416, 0.557);
    return (a + (b * cos((6.28318 * ((c * t) + d)))));
}

float Hash21(float2 p)
{
    p = frac((p * float2(123.34, 456.21)));
    p += dot(p, (p + 45.32));
    return frac((p.x * p.y));
}

float StarLayer(float2 uv)
{
    float2 gv = (frac(uv) - 0.5);
    float2 id = floor(uv);
    float m = 0.0;
    for (int y = -1; y <= 1; y++)
    {
        for (int x = -1; x <= 1; x++)
        {
            float2 offset = float2(x, y);
            float n = Hash21((id + offset));
            float size = frac((n * 345.32));
            float star = (smoothstep(0.1, 0.0, length(((gv - offset) - float2((n - 0.5), (frac((n * 34.0)) - 0.5))))) * size);
            m += star;
        }
    }
    return m;
}

void M(inout float2 uv)
{
    uv *= 1.0;
}

void Q(inout float2 uv)
{
    uv *= 1.0;
}

float sdBox(float3 p, float3 b)
{
    float3 q = (abs(p) - b);
    return (length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0));
}

float3 renderScene(float2 screenUV, float2 mouseM)
{
    float3 ro = float3((mouseM * 0.8), -2.5);
    float3 rd = normalize(float3((screenUV - (mouseM * 0.15)), 1.5));
    float d3;
    float t3 = 0.0;
    for (int i = 0; i < 80; i++)
    {
        float3 p = (ro + (rd * t3));
        p.xz = mul(rot((iTime * 0.15)), p.xz);
        p.xy = mul(rot((iTime * 0.15)), p.xy);
        d3 = sdBox(p, ((float3)(1.0)));
        if ((d3 < 0.001) || (t3 > 10.0))
        {
            break;
        }
        t3 += d3;
    }
    float3 layerColor = ((float3)(0.0));
    if (d3 < 0.001)
    {
        float3 p = (ro + (rd * t3));
        p.xz = mul(rot((iTime * 0.15)), p.xz);
        p.xy = mul(rot((iTime * 0.15)), p.xy);
        float3 n = abs(p);
        float2 faceUV = ((n.x > n.y) && (n.x > n.z) ? p.yz : (n.y > n.z ? p.xz : p.xy));
        float3 rd_local = rd;
        rd_local.xz = mul(rot((iTime * 1.0)), rd_local.xz);
        rd_local.xy = mul(rot((iTime * 1.0)), rd_local.xy);
        float2 parallaxOffset = ((float2)(0.0));
        if ((n.x > n.y) && (n.x > n.z))
        {
            parallaxOffset = (rd_local.yz * 0.08);
        }
        else
        {
            if (n.y > n.z)
            {
                parallaxOffset = (rd_local.xz * 0.08);
            }
            else
            {
                parallaxOffset = (rd_local.xy * 0.08);
            }
        }
        float2 uv = (faceUV + parallaxOffset);
        float2 uv3 = (faceUV + (parallaxOffset * 2.0));
        uv = mul(rot((iTime * 0.02)), uv);
        uv3 = mul(rot((iTime * 0.02)), uv3);
        float gridSize = 3.5;
        uv *= gridSize;
        uv3 *= gridSize;
        float t_shift = (iTime * 0.9);
        float row1 = floor(uv.y);
        float xShift1 = ((sin((t_shift + (row1 * 0.8))) + sin(((t_shift * 0.5) - (row1 * 1.3)))) * 1.2);
        uv.x += xShift1;
        uv3.x += xShift1;
        float col1 = floor(uv.x);
        float yShift1 = ((cos(((t_shift * 0.7) + (col1 * 0.6))) + sin(((t_shift * 1.2) + (col1 * 1.1)))) * 1.2);
        uv.y += yShift1;
        uv3.y += yShift1;
        float col2 = floor(uv.x);
        float yShift2 = ((sin(((t_shift * 1.1) - (col2 * 0.9))) * cos(((t_shift * 0.4) + (col2 * 0.5)))) * 1.0);
        uv.y += yShift2;
        uv3.y += yShift2;
        float row2 = floor(uv.y);
        float xShift2 = ((cos(((t_shift * 0.6) + (row2 * 1.4))) * sin(((t_shift * 1.3) - (row2 * 0.7)))) * 1.0);
        uv.x += xShift2;
        uv3.x += xShift2;
        float2 tileID = floor(uv);
        uv = (frac(uv) - 0.5);
        uv3 = (frac(uv3) - 0.5);
        float t = (iTime * 0.05);
        uv3.x = abs(uv3.x);
        uv3.y += (tan(((5.0 / 6.0) * 3.14159265359)) * 0.5);
        float2 nVec = N(((5.0 / 6.0) * 3.14159265359));
        float d = dot((uv3 - float2(0.5, 0.0)), nVec);
        uv3 -= ((nVec * max(0.0, d)) * 2.0);
        nVec = N(((2.0 / 3.0) * 3.14159265359));
        for (int i_sd = 0; i_sd < 4; i_sd++)
        {
            uv3 *= 1.25;
            uv3.x -= 0.6;
            M(uv);
            uv3.x = abs(uv3.x);
            uv3.x -= 0.3;
            uv3 -= ((nVec * min(0.0, dot(uv3, nVec))) * 2.0);
        }
        uv3 += (mouseM * 0.5);
        uv3 = mul(Rot(t), uv3);
        float3 col4 = ((float3)(0.0));
        for (float i_sd2 = 0.0; i_sd2 < 1.0; i_sd2 += (1.0 / 4.0))
        {
            float depth = frac((i_sd2 + t));
            float scale = lerp(15.0, 0.5, depth);
            float fade = (depth * smoothstep(1.0, 0.9, depth));
            col4 += (StarLayer(((uv3 * scale) + (i_sd2 * 453.2))) * fade);
        }
        M(uv);
        float2 uv0 = uv;
        for (float i_sd3 = 0.0; i_sd3 < 4.0; i_sd3++)
        {
            uv = (frac((uv * 1.5)) - 0.5);
            Q(uv);
            float dPattern = (length(uv) * exp(-length(uv0)));
            float3 col = palette((((length(uv0) + (i_sd3 * 0.4)) + (iTime * 0.2)) + (Hash21(tileID) * 0.8)));
            dPattern = (sin(((dPattern * 8.0) + iTime)) / 8.0);
            dPattern = abs(dPattern);
            dPattern = pow((0.01 / dPattern), 1.2);
            layerColor += ((col * dPattern) + (col4 * 0.2));
        }
        float2 gridLines = smoothstep(0.43, 0.49, abs(uv0));
        float border = (1.0 - max(gridLines.x, gridLines.y));
        float3 edgeGlow = ((palette((iTime * 0.1)) * max(gridLines.x, gridLines.y)) * 0.4);
        layerColor = ((layerColor * border) + edgeGlow);
        layerColor *= (1.0 - smoothstep(0.5, 1.5, length(uv0)));
    }
    else
    {
        layerColor = ((float3)((StarLayer(((screenUV * 3.0) - (mouseM * 0.2))) * 0.4)));
        layerColor += ((palette((iTime * 0.05)) * 0.05) / (length((screenUV - (mouseM * 0.1))) - 0.4));
    }
    return layerColor;
}

void mainImage(out float4 fragColor, float2 fragCoord)
{
    float2 screenUV = (((fragCoord * 2.0) - iResolution.xy) / iResolution.y);
    float2 mouseM = ((iMouse.xy - (iResolution.xy * 0.5)) / iResolution.y);
    if (iMouse.z <= 0.0)
    {
        mouseM = float2((sin((iTime * 0.05)) * 0.3), (cos((iTime * 0.03)) * 0.2));
    }
    float2 shiftDir = (normalize(screenUV) * length(screenUV));
    float aberrIntensity = (0.025 + (sin((iTime * 2.0)) * 0.008));
    float2 uvRed = (screenUV - (shiftDir * aberrIntensity));
    float2 uvGreen = screenUV;
    float2 uvBlue = (screenUV + (shiftDir * aberrIntensity));
    float rChannel = renderScene(uvRed, mouseM).r;
    float gChannel = renderScene(uvGreen, mouseM).g;
    float bChannel = renderScene(uvBlue, mouseM).b;
    float3 finalColor = float3(rChannel, gChannel, bChannel);
    finalColor *= (1.0 - smoothstep(0.5, 1.8, length(screenUV)));
    fragColor = float4(finalColor, 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
