// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass plain-GLSL fragment shader ('void main()'). The host
// MUST drive the resolution/time uniforms it references and draw a fullscreen quad in
// NDC for anything to render. Legacy FX9 style so the existing ShadowDusk pipeline can
// target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if SM4
    // DirectX (MonoGame's DirectX_11 profile defines SM4). mgfxc requires at least
    // SM 4.0 level 9.1 here and rejects vs_3_0/ps_3_0 outright.
    #define VS_SHADERMODEL vs_4_0_level_9_1
    #define PS_SHADERMODEL ps_4_0_level_9_1
#else
    // OpenGL (mgfxc caps it at SM 3.0) and FNA fx_2_0 (MojoShader SM 2-3).
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;

// Plain-GLSL fragment I/O bridged as static globals (see PSMain below).
static float4 gl_FragCoord;
static float4 gl_FragColor;

void main()
{
    float2 uv = (gl_FragCoord.xy / iResolution.xy);
    gl_FragColor = float4(uv.x, uv.y, 0.5, 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // Plain-GLSL gl_FragCoord has a BOTTOM-LEFT origin (y grows upward); our uv has a
    // top-left origin (uv.y=0 at the top). Flip Y back so gl_FragCoord.y grows upward,
    // matching the GLSL/ShaderToy reference orientation. .z=0, .w=1 like a real
    // gl_FragCoord (depth/1-over-w are not meaningful for a fullscreen pass).
    float2 pixel = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    gl_FragCoord = float4(pixel, 0.0, 1.0);
    gl_FragColor = float4(0.0, 0.0, 0.0, 1.0);
    main();
    return gl_FragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
