// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if OPENGL
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#else
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;
float iTime;

float3 mainImage(float2 fragCoord)
{
    float2 uv = (fragCoord / iResolution.xy);
    return float3(uv.x, uv.y, (0.5 + (0.5 * cos(iTime))));
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // 'returning' mainImage form: vec3/vec4 mainImage(in vec2 fragCoord) returns the
    // color. Same bottom-left-Y fragCoord as the standard harness.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float3 rgb = mainImage(fragCoord);
    return float4(rgb, 1.0);
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
