// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if OPENGL
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#else
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;
float iTime;

float map(float3 p)
{
    p = abs((frac(p) - 0.5));
    return (abs(min((length(p.xy) - 0.175), (min(p.x, p.y) + 1e-3))) + 1e-3);
}

float3 estimateNormal(float3 p)
{
    float eps = 0.001;
    return normalize(float3((map((p + float3(eps, 0.0, 0.0))) - map((p - float3(eps, 0.0, 0.0)))), (map((p + float3(0.0, eps, 0.0))) - map((p - float3(0.0, eps, 0.0)))), (map((p + float3(0.0, 0.0, eps))) - map((p - float3(0.0, 0.0, eps))))));
}

void mainImage(out float4 O, float2 C)
{
    float2 r = iResolution.xy;
    float2 uv = ((C - (0.5 * r)) / r.y);
    float t = iTime;
    float z = (frac(dot(C, sin(C))) - 0.5);
    float4 col = ((float4)(0.0));
    float4 p;
    for (float i = 0.0; (i < 77.0); i++)
    {
        p = float4((z * normalize(float3((C - (0.7 * r)), r.y))), (0.1 * t));
        p.z += t;
        float4 q = p;
        p.xy = mul(float2x2(cos(((2.0 + q.z) + float4(0, 11, 33, 0)))), p.xy);
        p.xy = mul(float2x2(cos((q + float4(0, 11, 33, 0)))), p.xy);
        float d = map(p.xyz);
        float3 pos = p.xyz;
        float3 lightDir = normalize(float3(0.3, 0.5, 1.0));
        float3 viewDir = normalize(float3(uv, 1.0));
        float3 n = estimateNormal(pos);
        float3 reflectDir = reflect(viewDir, n);
        float3 envColor = lerp(float3(0.8, 0.4, 0.8), ((float3)(1.0)), (0.5 + (0.5 * reflectDir.y)));
        float spec = pow(max(dot(reflectDir, lightDir), 0.0), 32.0);
        float4 baseColor = ((1.0 + sin((((0.5 * q.z) + length((p.xyz - q.xyz))) + float4(0, 4, 3, 6)))) / (0.5 + (2.0 * dot(q.xy, q.xy))));
        float3 finalColor = (((baseColor.rgb * 0.1) + (envColor * 0.9)) + (((float3)(spec)) * 1.2));
        col.rgb += (finalColor / d);
        z += (0.6 * d);
    }
    O = float4(tanh((col.rgb / 2e4)), 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
