// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if OPENGL
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#else
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;
float iTime;

float sdSphere(float3 p, float r)
{
    return (length(p) - r);
}

float map(float3 p)
{
    float sphere = sdSphere((p - float3(0.0, (0.2 * sin(iTime)), 0.0)), 1.0);
    float plane = (p.y + 1.0);
    return min(sphere, plane);
}

float3 calcNormal(float3 p)
{
    float2 e = float2(0.001, 0.0);
    return normalize(float3((map((p + e.xyy)) - map((p - e.xyy))), (map((p + e.yxy)) - map((p - e.yxy))), (map((p + e.yyx)) - map((p - e.yyx)))));
}

void mainImage(out float4 fragColor, float2 fragCoord)
{
    float2 uv = ((fragCoord - (0.5 * iResolution.xy)) / iResolution.y);
    float ca = (iTime * 0.5);
    float3 ro = float3((3.0 * sin(ca)), 1.0, (3.0 * cos(ca)));
    float3 ta = float3(0.0, 0.0, 0.0);
    float3 fwd = normalize((ta - ro));
    float3 right = normalize(cross(float3(0.0, 1.0, 0.0), fwd));
    float3 up = cross(fwd, right);
    float3 rd = normalize((((uv.x * right) + (uv.y * up)) + (1.5 * fwd)));
    float t = 0.0;
    float d = 0.0;
    bool hit = false;
    for (int i = 0; (i < 64); i++)
    {
        float3 p = (ro + (rd * t));
        d = map(p);
        if (d < 0.001)
        {
            hit = true;
            break;
        }
        t += d;
        if (t > 20.0)
        {
            break;
        }
    }
    float3 col = (float3(0.5, 0.65, 0.9) - (0.3 * uv.y));
    if (hit)
    {
        float3 p = (ro + (rd * t));
        float3 n = calcNormal(p);
        float3 lightDir = normalize(float3(0.6, 0.8, -0.4));
        float diff = max(dot(n, lightDir), 0.0);
        float3 h = normalize((lightDir - rd));
        float spec = pow(max(dot(n, h), 0.0), 32.0);
        float3 base = float3(0.85, 0.45, 0.30);
        col = ((base * (0.15 + (0.85 * diff))) + ((((float3)(1.0)) * spec) * 0.6));
    }
    col = pow(col, ((float3)(0.4545)));
    fragColor = float4(col, 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
