// =============================================================================
// ShaderToyEffect - generated by ShadowDusk shadertoy2fx (Phase 46 experiment)
// -----------------------------------------------------------------------------
// This .fx wraps a single-pass ShaderToy 'image' shader. The host MUST drive the
// ShaderToy uniforms (iResolution, iTime, iMouse, iChannelN, ...) every frame and
// draw a fullscreen quad in NDC for anything to render. Legacy FX9 style so the
// existing ShadowDusk pipeline can target OpenGL, DirectX, and FNA fx_2_0.
// =============================================================================

#if SM4
    // DirectX (MonoGame's DirectX_11 profile defines SM4). mgfxc requires at least
    // SM 4.0 level 9.1 here and rejects vs_3_0/ps_3_0 outright.
    #define VS_SHADERMODEL vs_4_0_level_9_1
    #define PS_SHADERMODEL ps_4_0_level_9_1
#else
    // OpenGL (mgfxc caps it at SM 3.0) and FNA fx_2_0 (MojoShader SM 2-3).
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#endif

float3 iResolution;

struct Kernel
{
    float w[4];
    float3 tint;
};
Kernel make_Kernel(float w[4], float3 tint)
{
    Kernel result;
    result.w[0] = w[0];
    result.w[1] = w[1];
    result.w[2] = w[2];
    result.w[3] = w[3];
    result.tint = tint;
    return result;
}


void mainImage(out float4 fragColor, float2 fragCoord)
{
    Kernel k;
    k.w[0] = 0.1;
    k.w[1] = 0.2;
    k.w[2] = 0.3;
    k.w[3] = 0.4;
    k.tint = float3(0.2, 0.6, 0.9);
    float s = (((k.w[0] + k.w[1]) + k.w[2]) + k.w[3]);
    fragColor = float4((k.tint * s), 1.0);
}


// Fullscreen-quad vertex shader. The host draws a quad/triangle whose POSITION is
// already in NDC ([-1,1]); we pass it straight through and derive a [0,1] uv.
struct VSInput  { float4 Position : POSITION; };
struct VSOutput { float4 Position : SV_Position; float2 UV : TEXCOORD0; };

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.Position = input.Position;
    // NDC xy in [-1,1] -> uv in [0,1]; y is flipped so uv.y=0 is the TOP of the screen.
    output.UV = float2(input.Position.x * 0.5 + 0.5, 0.5 - input.Position.y * 0.5);
    return output;
}

float4 PSMain(VSOutput input) : COLOR0
{
    // ShaderToy fragCoord has a BOTTOM-LEFT origin; our uv has a top-left origin
    // (uv.y=0 at the top). Flip Y back so fragCoord.y grows upward, matching the
    // ShaderToy reference orientation: fragCoord = (uv.x, 1 - uv.y) * iResolution.xy.
    float2 fragCoord = float2(input.UV.x, 1.0 - input.UV.y) * iResolution.xy;
    float4 fragColor = float4(0.0, 0.0, 0.0, 1.0);
    mainImage(fragColor, fragCoord);
    return fragColor;
}

technique ShaderToy
{
    pass P0
    {
        VertexShader = compile VS_SHADERMODEL VSMain();
        PixelShader  = compile PS_SHADERMODEL PSMain();
    }
}
