#nullable enable

using Shouldly;
using ShadowDusk.Compiler;
using ShadowDusk.Core;
using Xunit;

namespace ShadowDusk.Integration.Tests.Tests;

/// <summary>
/// Phase 54 — the empirical proof of the new DirectX12 target: compiles a shader with a
/// constant buffer AND a texture/sampler pair, then asserts the real MGFX profile byte (2,
/// matching MonoGame 3.8.5's <c>DirectX12ShaderProfile</c>), the <c>0xB00B00</c> wrapper
/// header, a DXBC-container-shaped DXIL payload, and non-empty structurally correct
/// reflection.
/// </summary>
[Trait("Category", "Integration")]
[Trait("Platform", "DirectX12")]
public sealed class DirectX12EffectCompilerTests
{
    // Modern SM6-safe syntax throughout (Texture2D/SamplerState/.Sample()/SV_Target) —
    // legacy sampler2D/tex2D/COLOR is rejected by DXC at DirectX12's forced vs_6_0/ps_6_0.
    private const string ParameterizedShader = """
        float4 Tint;
        Texture2D SpriteTexture;
        SamplerState SpriteTextureSampler;

        struct VOut { float4 Pos : SV_POSITION; float2 UV : TEXCOORD0; };

        VOut VS(float4 pos : POSITION0, float2 uv : TEXCOORD0)
        {
            VOut o;
            o.Pos = pos;
            o.UV = uv;
            return o;
        }

        float4 PS(VOut i) : SV_Target0
        {
            return SpriteTexture.Sample(SpriteTextureSampler, i.UV) * Tint;
        }

        technique T
        {
            pass P { VertexShader = compile vs_6_0 VS(); PixelShader = compile ps_6_0 PS(); }
        }
        """;

    [Fact]
    public async Task Compile_ParameterizedShader_ProducesRealDirectX12Container()
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(60));

        var result = await new EffectCompiler().CompileAsync(ParameterizedShader, new CompilerOptions
        {
            Target = PlatformTarget.DirectX12,
            SourceFileName = "DirectX12Parameterized.fx",
        }, cts.Token);

        result.IsSuccess.ShouldBeTrue(
            result.IsFailure ? string.Join("; ", result.Error.Select(e => $"{e.Code}: {e.Message}")) : "ok");

        var reader = MgfxBlobReader.Parse(result.Value.Data);
        reader.ProfileId.ShouldBe((byte)(2), customMessage: "MgfxProfile.DirectX12 is 2, matching real MonoGame 3.8.5's DirectX12ShaderProfile");
        reader.MgfxVersion.ShouldBe((byte)(11), customMessage: "DirectX12 always writes the v11 shader-record shape");

        reader.Shaders.Count().ShouldBe(2, customMessage: "one vertex + one pixel shader");
        foreach (var shader in reader.Shaders)
        {
            var dx12 = DirectX12ShaderCodeReader.Parse(shader.Bytecode);
            dx12.DxilMagicOk.ShouldBeTrue($"shader #{shader.Index} (isVertex={shader.IsVertex}) must wrap a DXBC-container-shaped DXIL blob");
        }

        reader.ConstantBuffers.ShouldNotBeEmpty("Tint must be reflected into a constant buffer");
        reader.Samplers.ShouldNotBeEmpty("SpriteTexture/SpriteTextureSampler must be reflected");
        reader.ParameterNames.ShouldContain("Tint");

        var pixelShader = reader.Shaders.Single(s => !s.IsVertex);
        pixelShader.ConstantBufferIndices.ShouldNotBeEmpty("the pixel shader stage must bind its constant buffer");
    }

    // A vertex shader that reads a GPU-generated system value alongside real attributes.
    private const string SystemValueShader = """
        struct VOut { float4 Pos : SV_POSITION; float2 UV : TEXCOORD0; };

        VOut VS(float4 pos : POSITION0, float2 uv : TEXCOORD0, uint vid : SV_VertexID)
        {
            VOut o;
            o.Pos = pos + float4(float(vid) * 0.0001, 0, 0, 0);
            o.UV = uv;
            return o;
        }

        float4 PS(VOut i) : SV_Target0 { return float4(i.UV, 0, 1); }

        technique T
        {
            pass P { VertexShader = compile vs_6_0 VS(); PixelShader = compile ps_6_0 PS(); }
        }
        """;

    [Fact]
    public async Task Compile_SystemValueVertexInput_ProducesNoPhantomAttribute()
    {
        // SV_VertexID / SV_InstanceID are generated by the GPU, not fed from a vertex
        // buffer. Minting a TEXCOORD attribute for one makes MonoGame's
        // VertexInputLayout demand an element the consumer's vertex declaration does not
        // provide, and the game dies at its first Draw with an unattributed E_INVALIDARG.
        // The SPIR-V path always skipped builtins; the DXIL path was fixed to match, with
        // nothing pinning it (no validation/ fixture declares SV_VertexID either).
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(60));

        var result = await new EffectCompiler().CompileAsync(SystemValueShader, new CompilerOptions
        {
            Target = PlatformTarget.DirectX12,
            SourceFileName = "DirectX12SystemValue.fx",
        }, cts.Token);

        result.IsSuccess.ShouldBeTrue(
            result.IsFailure ? string.Join("; ", result.Error.Select(e => $"{e.Code}: {e.Message}")) : "ok");

        var reader = MgfxBlobReader.Parse(result.Value.Data);
        var vertexShader = reader.Shaders.Single(s => s.IsVertex);

        vertexShader.Attributes.Count().ShouldBe(2, customMessage: "only POSITION0 and TEXCOORD0 come from the vertex buffer; SV_VertexID is GPU-generated");
        vertexShader.Attributes.Select(a => (a.Usage, a.Index))
            .ShouldBe(new[] { ((byte)0, (byte)0), ((byte)2, (byte)0) }, ignoreOrder: true);
    }

    // A typo'd vertex semantic: TEXCORD0 for TEXCOORD0. fxc/mgfxc accept it and default the
    // element to TextureCoordinate, printing a warning; ShadowDusk must do both.
    private const string TypoSemanticShader = """
        struct VOut { float4 Pos : SV_POSITION; float2 UV : TEXCOORD0; };

        VOut VS(float4 pos : POSITION0, float2 uv : TEXCORD0)
        {
            VOut o;
            o.Pos = pos;
            o.UV = uv;
            return o;
        }

        float4 PS(VOut i) : SV_Target0 { return float4(i.UV, 0, 1); }

        technique T
        {
            pass P { VertexShader = compile vs_6_0 VS(); PixelShader = compile ps_6_0 PS(); }
        }
        """;

    [Fact]
    public async Task Compile_UnrecognizedVertexSemantic_WarnsSd0104_AndStillCompiles()
    {
        // Bug-hunt 2026-07-27 N5, warning half. The DEFAULT is correct and must not move
        // (real mgfxc defaults the same way), so this is a WARNING, never a rejection —
        // but without it a typo silently mints a phantom TextureCoordinate attribute that
        // MonoGame then demands from the vertex declaration, and the only symptom is a
        // failed draw with no reference back to the shader.
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(60));

        var result = await new EffectCompiler().CompileAsync(TypoSemanticShader, new CompilerOptions
        {
            Target = PlatformTarget.DirectX12,
            SourceFileName = "DirectX12TypoSemantic.fx",
        }, cts.Token);

        result.IsSuccess.ShouldBeTrue(
            result.IsFailure ? string.Join("; ", result.Error.Select(e => $"{e.Code}: {e.Message}")) : "ok");

        var warning = result.Value.Warnings.SingleOrDefault(w => w.Code == "SD0104");
        warning.ShouldNotBeNull("the unrecognized semantic must surface as SD0104, as mgfxc warns");
        warning.Severity.ShouldBe(ShaderErrorSeverity.Warning);
        // DXIL reflection splits the semantic from its numeric index, so the name is
        // reported as "TEXCORD" with the index stated separately (SPIR-V, which keeps them
        // concatenated, reports "TEXCORD0").
        warning.Message.ShouldContain("TEXCORD", Case.Sensitive);
        warning.Message.ShouldContain("index 0", Case.Sensitive);
        warning.File.ShouldBe("DirectX12TypoSemantic.fx", "an MGCB build needs to know WHICH effect warned");

        // The output is unchanged: the fallback attribute is still written, exactly as before.
        var reader = MgfxBlobReader.Parse(result.Value.Data);
        var vertexShader = reader.Shaders.Single(s => s.IsVertex);
        vertexShader.Attributes.Select(a => (a.Usage, a.Index))
            .ShouldBe(new[] { ((byte)0, (byte)0), ((byte)2, (byte)0) }, ignoreOrder: true);
    }

    [Fact]
    public async Task Compile_AllSemanticsRecognized_EmitsNoSd0104()
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(60));

        var result = await new EffectCompiler().CompileAsync(ParameterizedShader, new CompilerOptions
        {
            Target = PlatformTarget.DirectX12,
            SourceFileName = "DirectX12CleanSemantics.fx",
        }, cts.Token);

        result.IsSuccess.ShouldBeTrue(
            result.IsFailure ? string.Join("; ", result.Error.Select(e => $"{e.Code}: {e.Message}")) : "ok");
        result.Value.Warnings.ShouldNotContain(w => w.Code == "SD0104",
            "POSITION0/TEXCOORD0 are both in the table; a false positive here would spam every clean build");
    }

    [Fact]
    public async Task Compile_WarnsSd0214_ExactlyWhenTheHostCannotSignDxil()
    {
        // Deliberately NOT a skip on either host: the assertion FLIPS by platform, so each
        // CI lane proves its own half. Windows pins the over-fire direction (a signed build
        // must not carry the warning); the Linux/macOS lanes pin that it fires at all —
        // which is the direction that matters, and which the developer's Windows render
        // gate structurally cannot see.
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(60));

        var result = await new EffectCompiler().CompileAsync(ParameterizedShader, new CompilerOptions
        {
            Target = PlatformTarget.DirectX12,
            SourceFileName = "DirectX12Signing.fx",
        }, cts.Token);

        result.IsSuccess.ShouldBeTrue(
            result.IsFailure ? string.Join("; ", result.Error.Select(e => $"{e.Code}: {e.Message}")) : "ok");

        bool warned = result.Value.Warnings.Any(w => w.Code == "SD0214");

        if (OperatingSystem.IsWindows())
        {
            warned.ShouldBeFalse(
                "dxil.dll signs the blob on Windows, so warning here would be a false positive");
        }
        else
        {
            warned.ShouldBeTrue(
                "dxil.dll signing is Windows-only, so this DXIL is unsigned and retail D3D12 "
                + "rejects it at pipeline-state creation — shipping that silently is the defect");
        }
    }
}
